# Generated by Django 4.2.10 on 2024-03-14 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_ingredient_author_ingredient_created_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='author',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='updated_on',
        ),
        migrations.AddField(
            model_name='recipe',
            name='author',
            field=models.CharField(default='User', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default='2024-03-15'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
